//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizSprint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Id { get; set; }
        public System.DateTime Score1 { get; set; }
        public string User_Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
